version: "3"

services: 
  zookeeper:
    image: yeasy/kafka:0.11.0.1
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"  # zk connection port
    command: bash -c 'bash /tmp/start_zk.sh'

  kafka: # kafka service
    image: yeasy/kafka:0.11.0.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    command: bash -c 'bash /tmp/start_kafka.sh'

  master:
    container_name: spark-master
    build: ./twitter-pipe
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    #spark-submit --packages org.apache.spark:spark-streaming-kafka-0-8_2.11:2.3.0  /app/store-job/start.py
    #spark-submit --packages org.apache.spark:spark-streaming-kafka-0-8_2.11:2.3.0 /app/sentiment-job/sentiment.py
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      #SPARK_PUBLIC_DNS: localhost
      KAFKA_HOST: kafka:9092
      ZOOKEEPER_HOST: zookeeper:2181
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./twitter-pipe/conf/master:/conf
      - ./twitter-pipe/data:/tmp/data
      - ./twitter-pipe:/app
      - ./data/parquet:/parquet
    depends_on:
      - kafka
  
  worker:
    container_name: spark-worker
    build: ./twitter-pipe 
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 4g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      #SPARK_PUBLIC_DNS: localhost
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
      - 8881:8881
    volumes:
      - ./twitter-pipe/conf/worker:/conf
      - ./twitter-pipe/data:/tmp/data
      - ./twitter-pipe:/app
    depends_on:
      - master

  influxdb:
    container_name: influxdb
    image: influxdb:alpine
    hostname: influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports: 
      - "8086:8086"

  twitter-stream:
    container_name: twitter-stream
    hostname: twitter-stream
    build: ./twitter-stream
    volumes: 
      - ./twitter-stream:/app
    ports:
      - "5000:5000"
    environment:
      KAFKA_HOST: kafka:9092
    restart: on-failure #hack restart until kafka is online
    depends_on:
      - kafka

  twitter-api:
    container_name: twitter-api
    image: node:8
    hostname: twitter-api
    ports:
      - "5001:5001"
    volumes:
      - ./twitter-api:/app
      - ./data/loki:/data
    depends_on:
      - twitter-stream

  twitter-ui:
    container_name: twitter-ui
    image: node:8
    hostname: twitter-ui
    ports: 
      - "5002:5002"
    volumes:
      - ./twitter-ui:/app

  twitter-proxy:
    container_name: twitter-proxy
    image: nginx:alpine
    hostname: twitter-proxy
    ports: 
      - "80:80"
    volumes:
       - ./twitter-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
       - ./twitter-ui/build:/app/www
    depends_on:
      - twitter-api